language: generic
sudo: required
services:
- docker
cache:
  directories:
  - .glide
jobs:
  include:
    - stage: Verify and Test
      script: make verify test
    - stage: Build and Make Image
      script: make build images
#script:
#- make verify build test images
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    repo: kubernetes-incubator/service-catalog
    all_branches: true
